"""Background job execution — non-blocking long commands (v4.30 W4.1).

Pattern absorbed from ouroboros's JobManager, reduced to SAMVIL's
file-is-SSOT philosophy (INV-1): every job is a JSON file under
`<project_root>/.samvil/jobs/<job_id>.json`, so job state survives MCP
server restarts and is inspectable without any tool.

Lifecycle: QUEUED → RUNNING → COMPLETED | FAILED | CANCELLED | INTERRUPTED

- start_job() spawns the command in its own session (process group) with
  stdout/stderr appended to a log file, then returns immediately.
- A watcher thread finalizes the job file when the process exits
  (heartbeat: the thread also bumps `last_heartbeat_at` while waiting).
- If the MCP server died mid-job, the next job_status() call detects the
  orphan via pid-liveness and marks it INTERRUPTED (zombie cleanup v1;
  full owner-process tracking is deferred).

Scale assumption: solo-dev — a handful of concurrent jobs, not a queue.
"""

from __future__ import annotations

import json
import os
import signal
import subprocess
import threading
import time
import uuid
from pathlib import Path
from typing import Any

from .claim_ledger import _locked  # same advisory-lock helper (W1.1)

_JOBS_DIR = "jobs"
_SAMVIL_DIR = ".samvil"

STATUS_RUNNING = "running"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"
STATUS_INTERRUPTED = "interrupted"

_TERMINAL = {STATUS_COMPLETED, STATUS_FAILED, STATUS_CANCELLED, STATUS_INTERRUPTED}

DEFAULT_TIMEOUT_SECONDS = 1800
_HEARTBEAT_INTERVAL = 5.0
_LOG_TAIL_CHARS = 4000


def _now() -> float:
    return time.time()


def _jobs_dir(project_root: str | Path) -> Path:
    d = Path(project_root) / _SAMVIL_DIR / _JOBS_DIR
    d.mkdir(parents=True, exist_ok=True)
    return d


def _job_path(project_root: str | Path, job_id: str) -> Path:
    # job_id is generated by us (uuid hex) — defensive strip anyway.
    safe = "".join(c for c in job_id if c.isalnum() or c in "-_")
    return _jobs_dir(project_root) / f"{safe}.json"


def _write_job(path: Path, data: dict[str, Any]) -> None:
    with _locked(path):
        tmp = path.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2))
        tmp.replace(path)


def _read_job(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _pid_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True


def _log_tail(project_root: str | Path, log_path: str) -> str:
    try:
        text = (Path(project_root) / log_path).read_text(
            encoding="utf-8", errors="ignore"
        )
        return text[-_LOG_TAIL_CHARS:]
    except OSError:
        return ""


def start_job(
    project_root: str,
    command: str,
    *,
    log_path: str = ".samvil/job.log",
    timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
    kind: str = "build",
) -> dict[str, Any]:
    """Spawn `command` (shell) in the project root; return immediately.

    The command runs in its own session so cancel can kill the whole
    process group. stdout/stderr append to `log_path` (INV-2).
    """
    root = Path(project_root).resolve()
    if not root.is_dir():
        raise ValueError(f"project_root is not a directory: {project_root}")
    timeout_seconds = max(10, min(int(timeout_seconds), 7200))

    job_id = f"job_{uuid.uuid4().hex[:12]}"
    path = _job_path(root, job_id)
    log_file = root / log_path
    log_file.parent.mkdir(parents=True, exist_ok=True)

    with log_file.open("a", encoding="utf-8") as logf:
        logf.write(f"\n── [{job_id}] $ {command}\n")
        logf.flush()
        proc = subprocess.Popen(
            command,
            shell=True,
            cwd=str(root),
            stdout=logf,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

    record: dict[str, Any] = {
        "job_id": job_id,
        "kind": kind,
        "command": command,
        "status": STATUS_RUNNING,
        "pid": proc.pid,
        "log_path": log_path,
        "timeout_seconds": timeout_seconds,
        "started_at": _now(),
        "last_heartbeat_at": _now(),
        "exit_code": None,
        "finished_at": None,
        "reason": "",
    }
    _write_job(path, record)

    watcher = threading.Thread(
        target=_watch,
        args=(path, proc, timeout_seconds),
        name=f"samvil-job-{job_id}",
        daemon=True,
    )
    watcher.start()
    return record


def _watch(path: Path, proc: subprocess.Popen, timeout_seconds: int) -> None:
    deadline = _now() + timeout_seconds
    while True:
        code = proc.poll()
        if code is not None:
            _finalize(path, code)
            return
        if _now() > deadline:
            _kill_group(proc.pid)
            _finalize(path, exit_code=None, status=STATUS_FAILED, reason="timeout")
            return
        data = _read_job(path)
        if data is not None:
            if data.get("status") == STATUS_CANCELLED:
                _kill_group(proc.pid)
                return  # cancel() already finalized the record
            data["last_heartbeat_at"] = _now()
            _write_job(path, data)
        time.sleep(_HEARTBEAT_INTERVAL)


def _finalize(
    path: Path,
    exit_code: int | None,
    status: str | None = None,
    reason: str = "",
) -> None:
    data = _read_job(path) or {}
    if data.get("status") in _TERMINAL:
        return
    if status is None:
        status = STATUS_COMPLETED if exit_code == 0 else STATUS_FAILED
    data.update(
        status=status,
        exit_code=exit_code,
        finished_at=_now(),
        reason=reason or data.get("reason", ""),
    )
    _write_job(path, data)


def _kill_group(pid: int) -> None:
    try:
        os.killpg(os.getpgid(pid), signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        pass


def job_status(project_root: str, job_id: str) -> dict[str, Any]:
    """Current job snapshot + log tail. Detects orphaned jobs."""
    path = _job_path(project_root, job_id)
    data = _read_job(path)
    if data is None:
        return {"job_id": job_id, "status": "not_found"}

    # Orphan detection: record says running, but the watcher (and maybe
    # the whole MCP server) is gone and so is the process.
    if data.get("status") == STATUS_RUNNING:
        stale = _now() - float(data.get("last_heartbeat_at", 0)) > 3 * _HEARTBEAT_INTERVAL
        if stale and not _pid_alive(int(data.get("pid", -1))):
            data["status"] = STATUS_INTERRUPTED
            data["reason"] = "owner process died (orphan detected on status read)"
            data["finished_at"] = _now()
            _write_job(path, data)

    out = dict(data)
    out["elapsed_seconds"] = round(
        (data.get("finished_at") or _now()) - float(data.get("started_at", _now())), 1
    )
    out["log_tail"] = _log_tail(project_root, str(data.get("log_path", "")))[-800:]
    return out


def job_result(project_root: str, job_id: str) -> dict[str, Any]:
    """Final result. status=running means not done yet — keep polling."""
    snap = job_status(project_root, job_id)
    if snap.get("status") == STATUS_RUNNING:
        return {"job_id": job_id, "status": STATUS_RUNNING, "done": False}
    snap["done"] = snap.get("status") in _TERMINAL
    snap["log_tail"] = _log_tail(
        project_root, str(snap.get("log_path", ""))
    )
    return snap


def cancel_job(project_root: str, job_id: str) -> dict[str, Any]:
    path = _job_path(project_root, job_id)
    data = _read_job(path)
    if data is None:
        return {"job_id": job_id, "status": "not_found"}
    if data.get("status") in _TERMINAL:
        return {"job_id": job_id, "status": data["status"], "note": "already terminal"}
    data["status"] = STATUS_CANCELLED
    data["finished_at"] = _now()
    data["reason"] = "cancelled by caller"
    _write_job(path, data)
    _kill_group(int(data.get("pid", -1)))
    return {"job_id": job_id, "status": STATUS_CANCELLED}


def list_jobs(project_root: str) -> list[dict[str, Any]]:
    out = []
    for p in sorted(_jobs_dir(project_root).glob("job_*.json")):
        data = _read_job(p)
        if data:
            out.append(
                {
                    "job_id": data.get("job_id"),
                    "kind": data.get("kind"),
                    "status": data.get("status"),
                    "started_at": data.get("started_at"),
                }
            )
    return out
