"""Tests-as-deliverable — make SAMVIL's verification travel with the app.

Until v4.30, samvil-qa verified each AC by driving Playwright *through
MCP, interactively*, then threw the steps away. QA "PASS" meant "the
harness checked it once," and the delivered project had zero tests — so
the user could never re-verify, and the output felt untrustworthy.

This module turns that one-shot verification into a committed artifact:

  - `playwright_config()` / `package_json_test_patch()` — the runnable
    test harness scaffold writes once.
  - `spec_from_acs()` — turns the structured steps the QA collected
    while verifying a feature into a real `@playwright/test` spec file,
    one `test()` per AC leaf.

After this, the delivered repo has `tests/e2e/*.spec.ts` + an
`npm test` script that re-runs exactly what SAMVIL checked. Trust moves
from "believe the harness" to "run it yourself."

Pure string generation — no I/O. The MCP tools in server.py own the
file writes (same pattern as materialize_*).
"""

from __future__ import annotations

import json
import re
from typing import Any

# Step schema (one dict per action the QA performed while verifying an AC):
#   {"action": "goto",          "url": "/"}
#   {"action": "click",         "role": "button", "name": "증가"}
#   {"action": "click",         "selector": "#submit"}
#   {"action": "fill",          "selector": "#title", "value": "buy milk"}
#   {"action": "press",         "key": "Space"}
#   {"action": "reload"}
#   {"action": "expect_text",   "selector": "main", "contains": "1"}
#   {"action": "expect_text",   "selector": "[data-count]", "equals": "0"}
#   {"action": "expect_visible","role": "heading", "name": "클릭 카운터"}
#   {"action": "expect_no_console_errors"}

_SUPPORTED_ACTIONS = frozenset(
    {
        "goto",
        "click",
        "fill",
        "press",
        "reload",
        "expect_text",
        "expect_visible",
        "expect_no_console_errors",
    }
)


def _js(s: str) -> str:
    """JSON-encode a string into a JS string literal (handles quotes/unicode)."""
    return json.dumps(str(s), ensure_ascii=False)


def _slug(value: str) -> str:
    norm = "".join(ch.lower() if ch.isalnum() else "-" for ch in str(value).strip())
    return "-".join(p for p in norm.split("-") if p)[:60] or "feature"


def _locator(step: dict[str, Any]) -> str:
    """Build a Playwright locator expression from a step's targeting keys."""
    if step.get("role") and step.get("name") is not None:
        return f"page.getByRole({_js(step['role'])}, {{ name: {_js(step['name'])} }})"
    if step.get("name") is not None and not step.get("selector"):
        return f"page.getByText({_js(step['name'])})"
    selector = step.get("selector") or "body"
    return f"page.locator({_js(selector)})"


def _render_step(step: dict[str, Any]) -> list[str]:
    action = step.get("action")
    if action not in _SUPPORTED_ACTIONS:
        # Unknown action → emit a comment, never crash the generator.
        return [f"    // (skipped unsupported step: {_js(action)})"]
    if action == "goto":
        return [f"    await page.goto({_js(step.get('url', '/'))});"]
    if action == "reload":
        return ["    await page.reload();"]
    if action == "press":
        return [f"    await page.keyboard.press({_js(step.get('key', 'Enter'))});"]
    if action == "click":
        return [f"    await {_locator(step)}.click();"]
    if action == "fill":
        return [
            f"    await {_locator(step)}.fill({_js(step.get('value', ''))});"
        ]
    if action == "expect_visible":
        return [f"    await expect({_locator(step)}).toBeVisible();"]
    if action == "expect_text":
        loc = _locator(step)
        if "equals" in step:
            return [f"    await expect({loc}).toHaveText({_js(step['equals'])});"]
        return [
            f"    await expect({loc}).toContainText({_js(step.get('contains', ''))});"
        ]
    if action == "expect_no_console_errors":
        # Console capture is wired at file scope; this asserts the buffer.
        return ["    expect(consoleErrors, consoleErrors.join('\\n')).toHaveLength(0);"]
    return []


def spec_from_acs(
    feature_name: str,
    acs: list[dict[str, Any]],
    *,
    base_path: str = "/",
) -> str:
    """Render one `@playwright/test` spec file for a feature.

    `acs` is a list of {ac_id, description, steps:[...]} — exactly what
    the QA collected while driving Playwright for that feature's leaves.
    Each AC becomes one `test()`. ACs with no steps become `test.skip`
    with a TODO so the gap is visible rather than silently absent.
    """
    needs_console = any(
        step.get("action") == "expect_no_console_errors"
        for ac in acs
        for step in (ac.get("steps") or [])
    )
    lines: list[str] = [
        "// AUTO-GENERATED by SAMVIL (tests-as-deliverable).",
        "// One test per acceptance criterion — re-run with `npm test`.",
        "// Safe to edit; SAMVIL appends new ACs and leaves edits in place.",
        "import { test, expect } from '@playwright/test';",
        "",
        f"test.describe({_js(feature_name)}, () => {{",
    ]
    if needs_console:
        lines += [
            "  let consoleErrors: string[];",
            "  test.beforeEach(({ page }) => {",
            "    consoleErrors = [];",
            "    page.on('console', (m) => {",
            "      if (m.type() === 'error') consoleErrors.push(m.text());",
            "    });",
            "  });",
        ]
    for ac in acs:
        ac_id = str(ac.get("ac_id") or "AC")
        desc = str(ac.get("description") or "")
        title = f"{ac_id}: {desc}".strip().rstrip(":")
        steps = ac.get("steps") or []
        lines.append("")
        if not steps:
            lines.append(
                f"  test.skip({_js(title)}, async ({{ page }}) => {{"
            )
            lines.append("    // TODO: SAMVIL had no recorded steps for this AC.")
            lines.append("  });")
            continue
        lines.append(f"  test({_js(title)}, async ({{ page }}) => {{")
        # Ensure a navigation happens first if the AC didn't include one.
        if not any(s.get("action") == "goto" for s in steps):
            lines.append(f"    await page.goto({_js(base_path)});")
        for step in steps:
            lines.extend(_render_step(step))
        lines.append("  });")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def playwright_config(base_url: str = "http://localhost:4173") -> str:
    """A minimal, CI-friendly playwright.config.ts that boots the app's
    own preview/dev server so `npm test` is self-contained."""
    return f"""// AUTO-GENERATED by SAMVIL (tests-as-deliverable).
import {{ defineConfig, devices }} from '@playwright/test';

export default defineConfig({{
  testDir: './tests/e2e',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: 'list',
  use: {{
    baseURL: {_js(base_url)},
    trace: 'on-first-retry',
  }},
  projects: [
    {{ name: 'chromium', use: {{ ...devices['Desktop Chrome'] }} }},
  ],
  webServer: {{
    // Build first so the test always reflects current source — otherwise
    // `npm test` silently passes against a stale dist/ build (a real
    // footgun caught in the B4 dogfood). Verifies the deployable bundle.
    command: 'npm run build && npm run preview',
    url: {_js(base_url)},
    reuseExistingServer: !process.env.CI,
    timeout: 180_000,
  }},
}});
"""


def package_json_test_patch(existing: dict[str, Any]) -> dict[str, Any]:
    """Return the patched package.json dict: a `test` script wired to
    Playwright, plus `test:headed`. Never clobbers an existing `test`
    script that isn't the default `echo "Error: no test specified"`."""
    pkg = dict(existing)
    scripts = dict(pkg.get("scripts") or {})
    current = scripts.get("test", "")
    if not current or "no test specified" in current:
        scripts["test"] = "playwright test"
        scripts.setdefault("test:headed", "playwright test --headed")
    pkg["scripts"] = scripts
    dev = dict(pkg.get("devDependencies") or {})
    dev.setdefault("@playwright/test", "^1.48.0")
    pkg["devDependencies"] = dev
    return pkg


def smoke_spec(base_path: str = "/") -> str:
    """A baseline spec so `npm test` is green from scaffold time (before
    any AC specs exist) — the app loads without console errors."""
    return spec_from_acs(
        "app smoke",
        [
            {
                "ac_id": "SMOKE",
                "description": "app loads without console errors",
                "steps": [
                    {"action": "goto", "url": base_path},
                    {"action": "expect_no_console_errors"},
                ],
            }
        ],
        base_path=base_path,
    )


def feature_spec_filename(feature_name: str) -> str:
    return f"tests/e2e/{_slug(feature_name)}.spec.ts"


def adversarial_spec(
    buttons: list[str],
    inputs: list[str],
    *,
    base_path: str = "/",
) -> str:
    """Generate a generic 'frustrated user' robustness spec (A3).

    This is NOT AC-driven — it probes the failure modes no AC anticipated:
    rapid double/triple clicks (race / double-submit), oversized and empty
    input (validation / layout), and reload mid-session (state integrity).
    The assertion is uniform: the app must not throw console errors or
    crash. `buttons`/`inputs` are role-names / selectors the QA discovered
    while driving the happy path.
    """
    lines: list[str] = [
        "// AUTO-GENERATED by SAMVIL (adversarial robustness pass, A3).",
        "// Probes failure modes no acceptance criterion anticipated:",
        "// rapid clicks, oversized/empty input, reload mid-session.",
        "import { test, expect } from '@playwright/test';",
        "",
        "test.describe('adversarial robustness', () => {",
        "  let consoleErrors: string[];",
        "  test.beforeEach(async ({ page }) => {",
        "    consoleErrors = [];",
        "    page.on('console', (m) => {",
        "      if (m.type() === 'error') consoleErrors.push(m.text());",
        "    });",
        "    page.on('pageerror', (e) => consoleErrors.push(String(e)));",
        f"    await page.goto({_js(base_path)});",
        "  });",
        "",
        "  const noErrors = () =>",
        "    expect(consoleErrors, consoleErrors.join('\\n')).toHaveLength(0);",
    ]
    for name in buttons:
        loc = f"page.getByRole(\"button\", {{ name: {_js(name)} }})"
        lines += [
            "",
            f"  test({_js(f'rapid-click survives: {name}')}, async ({{ page }}) => {{",
            f"    const b = {loc};",
            "    for (let i = 0; i < 8; i++) { await b.click({ force: true }).catch(() => {}); }",
            "    await noErrors();",
            "  });",
        ]
    for selector in inputs:
        loc = f"page.locator({_js(selector)})"
        lines += [
            "",
            f"  test({_js(f'hostile input survives: {selector}')}, async ({{ page }}) => {{",
            f"    const f = {loc};",
            "    await f.fill('x'.repeat(2000)).catch(() => {});",
            "    await f.fill('').catch(() => {});",
            "    await f.fill('   ').catch(() => {});",
            "    await noErrors();",
            "  });",
        ]
    lines += [
        "",
        "  test('reload mid-session stays stable', async ({ page }) => {",
        "    await page.reload();",
        "    await page.reload();",
        "    await noErrors();",
        "  });",
        "});",
        "",
    ]
    return "\n".join(lines)
