#!/usr/bin/env python3
"""Generate a section index at the top of large SKILL.legacy.md files (W3.3).

Degraded mode (MCP unreachable, P8) sends the LLM into a 1,400~1,700-line
legacy body to find one section. The index block maps every heading to its
line number so the fallback reader can jump (Read offset/limit) instead of
ingesting the whole file.

Idempotent: the block between the INDEX markers is regenerated in place.
Run after editing any indexed legacy file:

    python3 scripts/gen-legacy-index.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

TARGETS = (
    "skills/samvil-qa/SKILL.legacy.md",
    "skills/samvil-scaffold/SKILL.legacy.md",
    "skills/samvil-build/SKILL.legacy.md",
)

BEGIN = "<!-- LEGACY-INDEX:BEGIN (generated by scripts/gen-legacy-index.py — do not edit) -->"
END = "<!-- LEGACY-INDEX:END -->"

_HEADING = re.compile(r"^(#{2,3}) (.+)$")


def build_index(lines: list[str], start_offset: int) -> str:
    rows: list[str] = [
        BEGIN,
        "",
        "> **폴백 탐색 가이드 (P8)**: 전체를 읽지 말 것. 아래 인덱스에서 필요한",
        "> 섹션의 라인을 찾아 `Read(offset=<line>, limit=<다음 섹션까지>)`로",
        "> 해당 부분만 읽는다.",
        "",
        "| Line | Section |",
        "|---:|---|",
    ]
    in_code = False
    for i, line in enumerate(lines, start=start_offset):
        if line.lstrip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        m = _HEADING.match(line)
        if m:
            depth = "" if len(m.group(1)) == 2 else "&nbsp;&nbsp;↳ "
            title = m.group(2).strip().replace("|", "\\|")
            rows.append(f"| {i} | {depth}{title} |")
    rows.append("")
    rows.append(END)
    return "\n".join(rows)


def process(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Strip an existing index block.
    if BEGIN in text:
        b = next(i for i, l in enumerate(lines) if l.startswith(BEGIN.split(" ")[0]) and "LEGACY-INDEX:BEGIN" in l)
        e = next(i for i, l in enumerate(lines) if "LEGACY-INDEX:END" in l)
        # Also drop the single blank separator the generator appends after
        # the block — otherwise each regeneration grows the file by one
        # line and offsets oscillate.
        if e + 1 < len(lines) and lines[e + 1] == "":
            e += 1
        body_lines = lines[:b] + lines[e + 1 :]
    else:
        body_lines = lines

    # Insert position: after the H1 title (first line starting with "# ").
    insert_at = 0
    for i, line in enumerate(body_lines[:10]):
        if line.startswith("# "):
            insert_at = i + 1
            break

    # Line numbers in the final file: header block length affects offsets —
    # compute index against the final layout (body after insertion point is
    # shifted by the index height). Two-pass: build once to learn height,
    # rebuild with corrected offsets.
    placeholder = build_index(body_lines[insert_at:], start_offset=0)
    height = len(placeholder.splitlines()) + 1  # +1 blank line after END
    final_offset = insert_at + height + 1  # 1-based line of first body line
    index_block = build_index(body_lines[insert_at:], start_offset=final_offset)

    new_lines = (
        body_lines[:insert_at] + [index_block, ""] + body_lines[insert_at:]
    )
    new_text = "\n".join(new_lines)
    if not new_text.endswith("\n"):
        new_text += "\n"
    changed = new_text != text
    if changed:
        path.write_text(new_text, encoding="utf-8")
    return changed


def main() -> int:
    for rel in TARGETS:
        path = REPO / rel
        if not path.exists():
            print(f"  ✗ missing: {rel}")
            return 1
        changed = process(path)
        print(f"  {'✓ indexed' if changed else '✓ up-to-date'}: {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
