#!/usr/bin/env python3
"""Render `agents/ROLE-INVENTORY.md` from the canonical model_role map.

Runs off `mcp/samvil_mcp/model_role.DEFAULT_ROLES` so the inventory
document and the runtime mapping can never drift. Re-run whenever a new
agent is added; idempotent for no-op changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "mcp"))

from samvil_mcp.model_role import (  # noqa: E402
    ALLOWED_SECONDARY,
    DEFAULT_ROLES,
    OUT_OF_BAND,
    agents_by_role,
)


HEADER = """\
# Agent role inventory (v3.2 ⑤)

Source of truth: `mcp/samvil_mcp/model_role.DEFAULT_ROLES`. This file is
generated by `scripts/render-role-inventory.py`. Do not edit by hand —
update the mapping, then re-run the script.

## Summary

"""

FOOTER = """\

## Runtime enforcement

The v3.2 ledger (①) records `claimed_by` and `verified_by` for every
claim. The `validate_role_separation` MCP tool then checks:

1. `claimed_by != verified_by` (identity).
2. `verified_by` resolves to a Judge role (or an out-of-band verifier
   like `agent:user` or `agent:orchestrator-agent`).
3. `claimed_by` is not a Judge for its own subject.

Violations are rejected by the ledger, not just the tool — a skill cannot
bypass the check by writing directly to the JSONL file and still produce
a `status: verified` row without the Judge identity set correctly.

## Adding a new agent

1. Add the agent file under `agents/`.
2. Register the primary role in
   `mcp/samvil_mcp/model_role.DEFAULT_ROLES` (or in `OUT_OF_BAND` if
   it's not one of the six).
3. Run `python3 scripts/apply-role-tags.py` to inject the frontmatter.
4. Run `python3 scripts/render-role-inventory.py` to refresh this file.
5. Run the test suite.
"""


def render() -> str:
    rollup = agents_by_role()
    body_parts: list[str] = [HEADER]

    # Summary counts
    counts = {role: len(items) for role, items in rollup.items()}
    body_parts.append("| Role | Count | Write authority |\n")
    body_parts.append("|------|------:|-----------------|\n")
    descriptions = {
        "generator": "files in scope",
        "reviewer": "read + propose",
        "judge": "read + mark PASS/FAIL",
        "repairer": "edit only files listed by diagnosis",
        "researcher": "external + read only",
        "compressor": "handoff / seed summary (inline)",
        "out_of_band": "n/a — not part of six-role taxonomy",
    }
    for role in (
        "generator",
        "reviewer",
        "judge",
        "repairer",
        "researcher",
        "compressor",
        "out_of_band",
    ):
        body_parts.append(
            f"| `{role}` | {counts.get(role, 0)} | {descriptions[role]} |\n"
        )

    body_parts.append("\n## Agents by role\n")

    for role in (
        "generator",
        "reviewer",
        "judge",
        "repairer",
        "researcher",
        "compressor",
    ):
        body_parts.append(f"\n### {role}\n\n")
        for agent in rollup[role]:
            secondary = ALLOWED_SECONDARY.get(agent, ())
            if secondary:
                sec_str = ", ".join(r.value for r in secondary)
                body_parts.append(f"- `{agent}` (secondary: {sec_str})\n")
            else:
                body_parts.append(f"- `{agent}`\n")

    body_parts.append("\n### out_of_band\n\n")
    for agent in rollup["out_of_band"]:
        body_parts.append(f"- `{agent}`\n")

    body_parts.append(FOOTER)
    return "".join(body_parts)


def main() -> int:
    out_path = REPO / "agents" / "ROLE-INVENTORY.md"
    text = render()
    existing = out_path.read_text() if out_path.exists() else ""
    if text == existing:
        print(f"{out_path} already up to date")
        return 0
    out_path.write_text(text)
    print(f"wrote {out_path} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
